### PR TITLE
`InstCombine`: fix folding of `icmp eq i32 (ptrtoint ptr), null` in p200

### LINKED ISSUE #302: `InstCombine` does not fold `icmp eq i32 (ptrtoint Ptr), 0` into `icmp eq ptr Ptr, null` in address space 200
As per title.  For example:
```llvm
  %0 = tail call noundef align 4 dereferenceable_or_null(12) ptr addrspace(200) @alloc(i32 noundef signext 12, i32 noundef signext 4)
  %1 = ptrtoint ptr addrspace(200) %0 to i32
  %2 = icmp eq i32 %1, 0
  ; ... panic if null ...
```
could be folded into 
```llvm
  %0 = tail call noundef align 4 dereferenceable_or_null(12) ptr addrspace(200) @alloc(i32 noundef signext 12, i32 noundef signext 4)
  %2 = icmp eq ptr %0, null
  ; ... panic if null ...
```
but currently is not.

### PR DESCRIPTION
**Pull request by xdoardo**
Should, hopefully, fix #302.

### CODE REVIEW

**Comment by resistor** [comment]
This could probably go upstream as well.

File: llvm/lib/Transforms/InstCombine/InstCombineCompares.cpp [hunk 1]
```diff
@@ -6407,7 +6407,7 @@ Instruction *InstCombinerImpl::foldICmpWithCastOp(ICmpInst &ICmp) {
       PtrTy = cast<VectorType>(PtrTy)->getElementType();
       IntTy = cast<VectorType>(IntTy)->getElementType();
     }
-    return DL.getPointerTypeSizeInBits(PtrTy) == IntTy->getIntegerBitWidth();
+    return DL.getIndexTypeSizeInBits(PtrTy) == IntTy->getIntegerBitWidth();
```
Comment (resistor) [inline llvm/lib/Transforms/InstCombine/InstCombineCompares.cpp]: `icmp` is defined to compare the address bits, so I think this should used `getAddressSizeInBits` instead of `getIndexTypeSizeInBits`, though the result will be the same.

Comment (xdoardo) [reply llvm/lib/Transforms/InstCombine/InstCombineCompares.cpp]: Fixed here: [b4856ae](https://github.com/CHERIoT-Platform/llvm-project/pull/303/commits/b4856ae11d99d96d96c4c1712eb22e9f8432f2e4)

**Review by resistor — APPROVED** [review]
LGTM once tests complete

**Comment by resistor** [comment]
Forgot to squash, just rewrote it manually
